---
name: Formatting Workflow
permissions:
  contents: "read"

# yamllint disable-line rule:truthy
on:
  - pull_request
  - push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Prettier formatter
        run: npx prettier --check --config ./.prettierrc .
