---
name: Test Workflow
permissions:
  contents: "read"

# yamllint disable-line rule:truthy
on:
  - pull_request
  - push

jobs:
  jest:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "write"
      checks: "write"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Jest tests
        run: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json

      - name: Publish Jest coverage reports
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: report.json
          base-coverage-file: report.json
        if: github.event_name == 'pull_request'

  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          bundler-cache: true

      - name: Run RSpec tests with SimpleCov
        run: bundle exec rspec
